# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'samplePush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PushNotifications'

  # Pods for samplePush

  target 'samplePushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'samplePushUITests' do
    # Pods for testing
  end

end
